### ISSUE TITLE
Error on current Nukkit build

### ISSUE THREAD

**Issue by markkrueg** [ProjectInfinity/LeetTP#2]
This is happening on current Nukkit build #90

Not sure if it is a problem with LeetTP or Nukkit or something else. Let me know if there is anything you want me to test to try to fix this.

```
11:08:51 [INFO] Enabling LeetTP v1.0.1-b17
11:08:51 [ALERT] java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at cn.nukkit.command.SimpleCommandMap.register(SimpleCommandMap.java:94)
        at cn.nukkit.command.SimpleCommandMap.register(SimpleCommandMap.java:80)
        at cc.leet.leettp.LeetTP.onEnable(LeetTP.java:72)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:431)
        at cn.nukkit.Server.enablePlugin(Server.java:590)
        at cn.nukkit.Server.enablePlugins(Server.java:579)
        at cn.nukkit.Server.<init>(Server.java:423)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

11:08:51 [INFO] Disabling LeetTP v1.0.1-b17
```

**Comment by Pub4Game** [comment]
This is a problem of the plugin, Report the bug to the developer.

**Comment by markkrueg** [comment]
@Pub4Game Is this not the repository of the developer of the plugin LeetTP? If not; what is the repository?

**Comment by Pub4Game** [comment]
@markkrueg Ahaha, I thought you wrote in the repository Nukkit. sorry, I was inattentive

**Comment by ProjectInfinity** [comment]
@markkrueg Try http://ci.regularbox.com/job/LeetTP/22/
let me know if it is still happening.

**Comment by ProjectInfinity** [comment]
Reading the stacktrace again this does seem like an issue with Nukkit. I'm not really doing anything special, just getCommandMap().register(). :)

**Comment by ProjectInfinity** [comment]
It's indeed a Nukkit issue, gonna investigate it some more. :)

**Comment by ProjectInfinity** [comment]
It's happens in this build. http://ci.regularbox.com/job/Nukkit/30/
Build 29 does not have the issue. So time to check the commits.

**Comment by ProjectInfinity** [comment]
Found it. 
https://github.com/Nukkit/Nukkit/commit/9bd91fd454b441a2ea25519a643d6afabb2d4e5a

Issue is that Nukkit doesn't let my tpa command with the tp alias be registered as a result. Really dumb stuff, definitely a Nukkit issue since my alias doesn't override the built in command.

**Comment by ProjectInfinity** [comment]
Opened a ticket here.
https://github.com/Nukkit/Nukkit/issues/315

**Comment by markkrueg** [comment]
@ProjectInfinity Thanks for all that research!

**Comment by ProjectInfinity** [comment]
https://github.com/Nukkit/Nukkit/pull/316 :)
